Added Http Row with headers and params from row and its test cases
modakanalytics/http.almaren pull request #39
Opened 2023-08-21 17:48 UTC by praveenkumarb1207

@badrinathpatchikolla

2023-08-22 06:40 UTC, badrinathpatchikolla commented
@mantovani  Added New Method od HttpRow, which will have heads and params information within each request, will help in the iteration of each individual rest API.

Please verify this and let us know the points.


@praveenkumarb1207

2023-08-22 07:56 UTC, badrinathpatchikolla approved these changes

2023-08-30 02:52 UTC, mantovani requested changes
Please keep the original indentation. We can't check if the field exists for each row using Try is highly inefficient. Dataframe has an option to check if the field exists. Also you can't just ignore if "Try" fails....

First, check if the dataframe exists `row.schema.fields.contains(paramsCol)` if does you call getAs[Map[]] don't need the try, because if fail should fail, meaning the user sent wrong data structure. Please have a test use case for it as well.

Also the nomenclature doesn't make any sense

```
  val ParamsCol = "__REQUEST_PARAMS__"
  val HiddenParamsCol = "__REQUEST_HIDDEN_PARAMS__"
   val HeadersCol = "__REQUEST_HEADERS__"
```

Should be:

```
  val ParamsCol = "__PARAMS__"
  val HiddenParamsCol = "__HIDDEN_PARAMS__"
   val HeadersCol = "__HEADERS__"
```

2023-08-30 07:50 UTC, badrinathpatchikolla commented on README.md
>  spark-shell --master "local[*]" --packages "com.github.music-of-the-ainur:almaren-framework_2.12:0.9.9-3.2,com.github.music-of-the-ainur:http-almaren_2.12:1.2.7-3.2"
change the http almaren type

2023-08-30 18:13 UTC, mantovani approved these changes

2023-08-31 07:07 UTC, closed without merging